name: toffee
description: Toffee Life Insurance.

version: 1.0.0+1

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bottom_navy_bar: ^6.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.0
  easy_localization: 3.0.3
  font_awesome_flutter: ^10.0.0
  fluro: ^2.0.0
  flutter_inner_drawer: ^1.0.0
  flutter_svg: ^2.0.0
  google_fonts: ^6.0.0
  image_picker: ^1.0.0
  json_serializable: ^6.0.0
  provider: ^6.0.0
  responsive_widgets: ^2.0.1
  share: ^2.0.0
  shared_preferences: ^2.0.0
  sqflite: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - langs/en-US.json
    - langs/hi-IN.json
    - images/
