name: toffee
description: Toffee Life Insurance.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bottom_navy_bar: ^5.3.2
  carousel_slider: ^1.4.1
  cupertino_icons: ^0.1.3
  easy_localization: ^2.1.0+0
  font_awesome_flutter: ^8.8.1
  fluro: ^1.6.2
  flutter_inner_drawer: ^0.5.5
  flutter_svg: ^0.17.3+1
  google_fonts: ^0.3.10
  image_picker: ^0.6.4
  json_serializable: ^3.3.0
  provider: ^4.0.4
  responsive_builder: ^0.1.5
  responsive_widgets: ^2.0.1
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - google_fonts/
    - assets/langs/en-US.json
    - assets/langs/hi-IN.json
    - assets/images/
